version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: user_service_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/user_service_development
      RAILS_ENV: development
    depends_on:
      - db
    # volumes:
    #   - .:/app
    #   - bundle_cache:/usr/local/bundle
    command: ./bin/rails server -p 3001 -b 0.0.0.0

volumes:
  postgres_data:
  # bundle_cache:
