source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

# Rails framework
gem "rails", "~> 7.1.4"
gem "puma", "~> 6.0"
gem "bootsnap", require: false

# Database
gem "pg", "~> 1.1"
gem "redis", "~> 5.0"

# API and JSON
gem "jbuilder"
gem "rack-cors"

# Authentication and Authorization
gem "jwt"
gem "bcrypt", "~> 3.1.7"
gem "devise"
gem "devise-jwt"

# Validation and serialization
gem "active_model_serializers"
gem "dry-validation"
gem "validates_email_format_of"

# Background jobs
gem "sidekiq", "~> 7.0"

# Monitoring and logging
gem "lograge"
gem "sentry-ruby"
gem "sentry-rails"

# Email
gem "mailgun-ruby"

# Health checks
gem "health_check"

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "shoulda-matchers"
  gem "database_cleaner-active_record"
  gem "simplecov", require: false
end

group :development do
  gem "listen", "~> 3.3"
  gem "spring"
  gem "annotate"
  gem "bullet"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
  gem "vcr"
  gem "webmock"
end
